-- AlterTable
-- 將 Invoice 表中除了 invNum 以外的欄位改為可選（允許 NULL）

ALTER TABLE "Invoice" ALTER COLUMN "v" DROP NOT NULL;
ALTER TABLE "Invoice" ALTER COLUMN "code" DROP NOT NULL;
ALTER TABLE "Invoice" ALTER COLUMN "msg" DROP NOT NULL;
ALTER TABLE "Invoice" ALTER COLUMN "invDate" DROP NOT NULL;
ALTER TABLE "Invoice" ALTER COLUMN "sellerName" DROP NOT NULL;
ALTER TABLE "Invoice" ALTER COLUMN "amount" DROP NOT NULL;
ALTER TABLE "Invoice" ALTER COLUMN "invStatus" DROP NOT NULL;
ALTER TABLE "Invoice" ALTER COLUMN "invPeriod" DROP NOT NULL;
ALTER TABLE "Invoice" ALTER COLUMN "sellerBan" DROP NOT NULL;
ALTER TABLE "Invoice" ALTER COLUMN "invoiceTime" DROP NOT NULL;

